# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: rbordin <rbordin@student.42.fr>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/09/11 17:11:54 by rbordin           #+#    #+#              #
#    Updated: 2023/12/04 11:41:57 by rbordin          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all:
	c++ -Werror -Wextra -Wall  main.cpp ClapTrap.cpp -o claptrap

fclean:
	rm -f *.o
	rm -f claptrap