# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: riccardobordin <riccardobordin@student.    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/09/12 11:59:19 by rbordin           #+#    #+#              #
#    Updated: 2023/12/03 14:32:16 by riccardobor      ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all:
	g++ -Wall -Wextra -Werror ClapTrap.cpp ScavTrap.cpp main.cpp -o ScavTrap

fclean:
	rm -f *.o
	rm -f ScavTrap