# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: rbordin <rbordin@student.42.fr>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/09/17 13:18:10 by riccardobor       #+#    #+#              #
#    Updated: 2023/12/18 12:22:58 by rbordin          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all:
	c++ -Werror -Wextra -Wall -std=c++98 main.cpp Form.cpp Bureaucrat.cpp -o form

fclean:
	rm -f form