# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: riccardobordin <riccardobordin@student.    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/09/10 16:19:08 by riccardobor       #+#    #+#              #
#    Updated: 2023/12/03 14:26:08 by riccardobor      ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all:
	c++ -Werror -Wextra -Wall -std=c++98 main.cpp Harl.cpp -o harl

fclean:
	rm -f *.o
	rm harl