# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: riccardobordin <riccardobordin@student.    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/09/11 12:17:29 by rbordin           #+#    #+#              #
#    Updated: 2023/12/03 14:26:08 by riccardobor      ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all:
	c++ -Werror -Wextra -Wall -std=c++98	main.cpp Fixed.cpp -o Fixed
	
fclean:
	rm -f Fixed