# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: riccardobordin <riccardobordin@student.    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/09/11 15:31:18 by rbordin           #+#    #+#              #
#    Updated: 2023/12/03 14:26:08 by riccardobor      ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all:
	c++ -Werror -Wextra -Wall main.cpp Fixed.cpp -o fixed

fclean:
	rm -f *.o
	rm -f fixed